### ISSUE TITLE
Exception with AutoListener

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#26] opened 2019-04-09 01:10 UTC
### Full output of /ncp version
---- Version information ----
#### Server ####
git-Paper-588 ~MC: 1.13.2~
  detected: 1.13.2
#### NoCheatPlus ####
Plugin: 3.16.1-SNAPSHOT-b1153-CustomFork
MCAccess: 1.4.5-1.12.2|? / CB-Reflect
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations~NCP~ 1.0 | mcMMO~cncp~ 2.3
#### Related Plugins ####
CompatNoCheatPlus v6.6.6-SNAPSHOT-sMD5NET-b91 | ProtocolLib v4.4.0 | ProtocolSupport v4.29-dev

### Describe the issue
This error pops up in console: https://pastebin.com/GjxmT3TY

### How to reproduce the issue
Unknown. When I joined the server, I was attacked by a zombie and I attacked back which outputted that error in console. I though it was that, so I tried getting attack by a zombie again and attacking back, but It wasn't able to trigger it.

### Extra links/Videos (Including debug logs)
Just a link to the pastebin: https://pastebin.com/GjxmT3TY

### Any possible config options changed or plugins that may cause interference?
No config change. I built the latest commit and tested it. So it might be something with the new changes that's been made to the plugin?

**Comment by CaptainObvious0** [comment] 2019-04-09 01:36
Looks like the players location is returning null. I can't say exactly whats causing this, but I can assume it may be connected with recently joining the server. No reproduction steps/patterns will make it hard to see if the issue is fixed or not. I'll add a nullcheck before checking but other than that I can't do much.

Did this error appear once or was it repeated multiple times?

**Comment by CaptainObvious0** [comment] 2019-04-09 01:40
Added a nullcheck with 7f65bd1

Please note that you should build as of the latest release, rather than the latest commit. Sometimes I use GitHub as a reference point or a backup and not all commits pushed may be fully tested.

Closing for now, please reopen if you still experience any issues.

**Closed as completed by CaptainObvious0** 2019-04-09 01:40 UTC
Labels: Fork Issue
