### ISSUE TITLE
Bubble Column Stutter 

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#17] opened 2019-04-04 04:54 UTC
When going up a bubble column elevator, you'll experience stuttering while going up.

**Comment by CaptainObvious0** [comment] 2019-04-04 12:07
Need more information than that. Steps to reproduce, a video, and what check is being flagged.

I’m not sure what a “bubble column elevator” is, so you will need to define that as well.

**Comment by Kyrobi** [comment] 2019-04-04 23:29
How to reproduce and what a bubble column elevator is included in the video.  Regards to the what checks were flagged, it doesn't display (nor in console). However,disabling survivalfly and creativefly checks got rid of the stutter when going up a bubble column.

https://youtu.be/hYvZZ_Hix5s

**Comment by CaptainObvious0** [comment] 2019-04-05 00:35
Ah, I was not aware that was apart of the 1.13 water changes. Thanks for clarifying.

Attempting to fix this will be a little tricky, since I'm not sure there's anything in the spigot api for detecting bubbles in the water, thus requiring a workaround. I'll probably be able to detect if the block (not water) below the player is soul sand or a magma block and allow a faster vertical speed. 

Thanks for the report. I'll do some testing of the method described above and see if it is a valid option.

**Comment by CaptainObvious0** [comment] 2019-04-06 01:37
A fix was actually a lot easier than expected, since water with bubbles has a separate material name. 

Fixed with 62f598a , still need to set magic speeds. Putting priority on making it usable rather than taking time to fine-tune the actual speed.

**Closed as completed by CaptainObvious0** 2019-04-06 01:37 UTC
Labels: 1.13/1.14 Issue
