### ISSUE TITLE
Exception with AutoListener - Fastclick ArithmeticException: / by zero

### ISSUE THREAD

**Issue by mibby** [CaptainObvious0/NoCheatPlus#16] opened 2019-04-02 05:08 UTC
@CaptainObvious0 

Compiled as of commit https://github.com/CaptainObvious0/NoCheatPlus/commit/7c14c1362994c02802ba6153326a69caf4f0ea82
```
[22:07:32] [Craft Scheduler Thread - 19/ERROR]: [NoCheatPlus] Exception with AutoListener(fr.neatmonster.nocheatplus.checks.inventory.InventoryListener.onInventoryClick/org.bukkit.event.inventory.InventoryClickEvent/LOWEST), processing org.bukkit.event.inventory.InventoryClickEvent: InvocationTargetException -> log once id=623170307
[22:07:32] [Craft Scheduler Thread - 19/ERROR]: [NoCheatPlus] Exception:
java.lang.reflect.InvocationTargetException
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:566)
	fr.neatmonster.nocheatplus.event.mini.MultiListenerRegistry$AutoListener.onEvent(MultiListenerRegistry.java:82)
	fr.neatmonster.nocheatplus.event.mini.MiniListenerNode.onEvent(MiniListenerNode.java:157)
	fr.neatmonster.nocheatplus.event.mini.EventRegistryBukkit$4.execute(EventRegistryBukkit.java:124)
	co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
	org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
	net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2287)
	net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
	net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
	net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
	java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
	net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1017)
	net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
	net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939)
	net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
	java.base/java.lang.Thread.run(Thread.java:834)
caused by:
java.lang.ArithmeticException: / by zero
	fr.neatmonster.nocheatplus.checks.inventory.FastClick.fastClickChest(FastClick.java:173)
	fr.neatmonster.nocheatplus.checks.inventory.InventoryListener.onInventoryClick(InventoryListener.java:281)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:566)
	fr.neatmonster.nocheatplus.event.mini.MultiListenerRegistry$AutoListener.onEvent(MultiListenerRegistry.java:82)
	fr.neatmonster.nocheatplus.event.mini.MiniListenerNode.onEvent(MiniListenerNode.java:157)
	fr.neatmonster.nocheatplus.event.mini.EventRegistryBukkit$4.execute(EventRegistryBukkit.java:124)
	co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
	org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
	net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2287)
	net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
	net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
	net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
	java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
	net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1017)
	net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
	net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939)
	net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
	java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by CaptainObvious0** [comment] 2019-04-02 11:40
More information will be needed here on now to reproduce the issue. Does it happen every time? Error is with calculating VL. I guess for now a safeguard can be placed to prevent it from being zero.

**Comment by CaptainObvious0** [comment] 2019-04-02 12:06
Attempted fix for now, b304aff 

I’m still going to need more information. Are these clicks within a custom gui? If it is, that may be the issue because the user may have never clicked a chest before opening the inventory.

**Comment by mibby** [comment] 2019-04-02 20:58
I do have many uses of custom GUI containers being opened for server menus and commands. I'll update later tonight and let you know if the exceptions still occur.

**Comment by CaptainObvious0** [comment] 2019-04-02 21:05
Alright, then I should add something to make sure they are not zero before checking.

I’m not at my computer right now so I can’t verify this, but adding the inventory name to the FastClick.excluded list should not check the player for FastClick in that inventory. I’m just not sure if it extends to the fastClickChest check.

**Comment by CaptainObvious0** [comment] 2019-04-03 01:16
There should no longer be a / 0 error. Last commit did not completely fix it. 4a3d926 

fastClick.Exclude list will not exclude fastClickChest check. Please add your GUI names into the config so that they are not checked. This will prevent false positives since most FastClick false positives occur with GUI's since all inventory clicks are cancelled, and FastClick does not ignore cancelled events. e8e2645 

Closing this as it should be fixed.

**Closed as completed by CaptainObvious0** 2019-04-03 01:16 UTC
Labels: Fork Issue
